# Generated by Django 5.0.4 on 2024-04-20 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_purchase_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 13, 16, 1, 166459, tzinfo=datetime.timezone.utc)),
        ),
    ]
